### ISSUE TITLE
Remote control emulation

### ISSUE THREAD

**Issue by procount** [bulletmark/FireBirdLib#2]
Hi,
Do you know if it is possible for a TAP to  emulate remote control keys fed in via the serial or USB ports?
My mother-in-law bought a new TV but the remote control clashes with her UK Toppy TF5800. I was thinking if I can get a TAP to inject keycodes fed from another port, I could perhaps emulate a remote control over wifi or something instead. 🤷‍♂️

**Comment by bulletmark** [comment]
Sorry, don't know. Ask on the various Topfield forums.
